# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27cb4c8274962edab5c9c9d8a5448ac69fc042157a02430c69d4789e875341dfdaf800a8ed664ffb9b79b9e4ac596068690bb30c7250221e0032042c895d121a

test:
  secret_key_base: 9f57e01f1b023158cfe893a68f5650cdb68a0edc3eacb9f98dd38ddfd68f3a1f3684e18e33a415b5668e72be05e601d97c687ef999456294bbb359078189d1af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
